tasks:
  - name: appwrite
    init: |
      docker-compose pull --include-deps appwrite telegraf influxdb traefik
    command: |
      docker-compose up
  
  - name: appwriteCLI
    init: |
      curl -sL https://appwrite.io/cli/install.sh | bash
      
ports:
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
